#!/bin/sh

# get the latest software
apt-get update 

# remove unnecessary lenses
sudo apt-get autoremove unity-lens-music unity-lens-photos unity-lens-gwibber unity-lens-shopping unity-lens-video -y

# install typical packages
apt-get install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra texlive-fonts-recommended vim -y
apt-get install keepassx shutter inkscape filezilla pdftk openjdk-7-jdk calibre xchat nautilus-open-terminal sound-juicer openjdk-7-source xournal -y

# Setup Git defaults

# Create a ~/.gitignore in your user directory
cd ~/
touch .gitignore

# Exclude bin and .metadata directories
echo "bin" >> .gitignore
echo ".metadata" >> .gitignore
echo "*~" >> .gitignore
echo "target/" >> .gitignore

# Configure Git to use this file
# as global .gitignore

git config --global core.excludesfile ~/.gitignore
git config --global branch.autosetuprebase always 


